name: Continuous integration

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: jurplel/install-qt-action@v2
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: jurplel/install-qt-action@v2
      - uses: actions-rs/cargo@v1
        with:
          command: check


  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          
        with:
          submodules: recursive
      - uses: jurplel/install-qt-action@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
